# Docker version 20.10.2
# docker-compose version 1.27.4

version: "3"

services:
  grafana:  
    image: grafana/grafana:latest
    container_name: grafana_container
    ports:
      - "3000:3000"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_container
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_config/:/etc/prometheus/
      

